#!/usr/bin/env python3
"""platform/jira_templates.py - Phase 10: Jira update generator.

Generates ready-to-paste Jira ticket update text for all lifecycle stages.

Stages: discovery-complete | renewal-started | renewal-complete |
        validation-complete | issue-detected | failure | risk-identified
"""

from datetime import datetime
from platform.logger import get_logger


class JiraTemplates:

    def __init__(self, logger=None):
        self.log = logger or get_logger()

    def generate(self, cert_name: str, stage: str, details: dict = None) -> str:
        details = details or {}
        stage = stage.lower().replace("_", "-")
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        generators = {
            "discovery-complete": self._discovery_complete,
            "renewal-started": self._renewal_started,
            "renewal-complete": self._renewal_complete,
            "validation-complete": self._validation_complete,
            "issue-detected": self._issue_detected,
            "failure": self._failure,
            "risk-identified": self._risk_identified,
        }

        gen = generators.get(stage)
        if not gen:
            return f"Unknown stage: {stage}. Available: {', '.join(generators.keys())}"

        template = gen(cert_name, now, details)
        self.log.info("Jira update generated for '%s' stage '%s'", cert_name, stage)
        return template

    def _discovery_complete(self, cert_name, ts, d):
        vault = d.get("key_vault", "[KEY_VAULT]")
        app = d.get("app_service", "[APP_SERVICE]")
        expiry = d.get("expiration", "[EXPIRY_DATE]")
        days = d.get("days_until_expiry", "[DAYS]")
        return f"""h2. Certificate Discovery Complete — {cert_name}
*Updated:* {ts}
*Status:* Discovery Complete

h3. Summary
Certificate inventory discovery has been completed for *{cert_name}*.

h3. Details
||Field||Value||
|Certificate|{cert_name}|
|Key Vault|{vault}|
|App Service|{app}|
|Expiration|{expiry}|
|Days Remaining|{days}|

h3. Next Steps
# Review certificate expiry and risk level
# Initiate renewal if expiry is within 90 days
# Update this ticket with renewal status

_Generated by SSL Certificate Lifecycle Platform v1.0.0_"""

    def _renewal_started(self, cert_name, ts, d):
        return f"""h2. Certificate Renewal Started — {cert_name}
*Updated:* {ts}
*Status:* In Progress

h3. Actions Taken
* CSR generated for {cert_name}
* CSR submitted to Sectigo for validation
* Awaiting certificate issuance

h3. Expected Timeline
Certificate issuance typically takes 1-2 business days after domain validation.

h3. Next Steps
# Monitor Sectigo portal for certificate issuance
# Download certificate files when issued
# Build certificate chain and PFX
# Import into Key Vault (with approval)

_Generated by SSL Certificate Lifecycle Platform v1.0.0_"""

    def _renewal_complete(self, cert_name, ts, d):
        vault = d.get("key_vault", "[KEY_VAULT]")
        new_expiry = d.get("new_expiration", "[NEW_EXPIRY]")
        version = d.get("version", "[VERSION]")
        return f"""h2. Certificate Renewal Complete — {cert_name}
*Updated:* {ts}
*Status:* Renewal Complete

h3. Summary
Certificate *{cert_name}* has been successfully renewed and imported into Key Vault.

h3. Details
||Field||Value||
|Certificate|{cert_name}|
|Key Vault|{vault}|
|New Expiration|{new_expiry}|
|New Version|{version}|

h3. Completed Actions
* [x] New certificate issued by Sectigo
* [x] Certificate chain built and verified
* [x] PFX package created and validated
* [x] Imported into Key Vault: {vault}
* [x] Post-import validation passed

h3. Next Steps
# Verify App Service is serving the new certificate
# Update HTTPS endpoint monitoring
# Close this ticket

_Generated by SSL Certificate Lifecycle Platform v1.0.0_"""

    def _validation_complete(self, cert_name, ts, d):
        result = d.get("validation_result", "PASSED")
        checks_passed = d.get("checks_passed", "7/7")
        return f"""h2. Post-Import Validation Complete — {cert_name}
*Updated:* {ts}
*Status:* Validation {result}

h3. Validation Results
*Checks Passed:* {checks_passed}
*Overall Status:* {result}

h3. Checks Performed
* [x] Certificate exists in Key Vault
* [x] Certificate enabled
* [x] Certificate not expired
* [x] Key Vault status OK
* [x] App Service SSL binding present
* [x] HTTPS endpoint reachable (HTTP 200)
* [x] Live certificate matches imported certificate

See ValidationReport.md (attached) for full details.

_Generated by SSL Certificate Lifecycle Platform v1.0.0_"""

    def _issue_detected(self, cert_name, ts, d):
        issue = d.get("issue", "[ISSUE_DESCRIPTION]")
        severity = d.get("severity", "HIGH")
        return f"""h2. Certificate Issue Detected — {cert_name}
*Updated:* {ts}
*Status:* Issue Detected
*Severity:* {severity}

h3. Issue Summary
{issue}

h3. Affected Resources
||Resource||Value||
|Certificate|{cert_name}|
|Key Vault|{d.get("key_vault", "[KEY_VAULT]")}|
|App Service|{d.get("app_service", "[APP_SERVICE]")}|

h3. Immediate Actions Required
# Investigate root cause
# Check Key Vault firewall access
# Verify App Service synchronization
# Escalate if not resolved within SLA

_Generated by SSL Certificate Lifecycle Platform v1.0.0_"""

    def _failure(self, cert_name, ts, d):
        error = d.get("error", "[ERROR_MESSAGE]")
        step = d.get("step", "[FAILED_STEP]")
        return f"""h2. Certificate Operation FAILED — {cert_name}
*Updated:* {ts}
*Status:* FAILED
*Failed Step:* {step}

h3. Error Details
{{code}}{error}{{code}}

h3. Troubleshooting Steps
# Check logs: logs/CERT_LIFECYCLE_*.log
# Run health check: python platform/main.py health-check
# Verify Azure authentication: az account show
# Check Key Vault firewall: ensure current IP is allowed
# See TROUBLESHOOTING.md for common issues

h3. Escalation
If issue persists after troubleshooting, escalate to cloud operations team.

_Generated by SSL Certificate Lifecycle Platform v1.0.0_"""

    def _risk_identified(self, cert_name, ts, d):
        days = d.get("days_until_expiry", "[DAYS]")
        risk = d.get("risk_level", "HIGH")
        return f"""h2. Certificate Risk Identified — {cert_name}
*Updated:* {ts}
*Status:* Risk Identified
*Risk Level:* {risk}

h3. Risk Summary
Certificate *{cert_name}* expires in *{days} days*.
{d.get("narrative", "")}

h3. Recommended Actions
# Begin renewal process immediately
# Allocate engineer time for renewal workflow
# Target completion 7 days before expiry
# Update this ticket upon renewal completion

_Generated by SSL Certificate Lifecycle Platform v1.0.0_"""

