#!/usr/bin/env python3
"""platform/reporting.py - Phase 7: Multi-format report generation (MD/HTML/CSV/JSON)."""

import csv, json, os
from datetime import datetime
from platform.logger import get_logger


REPORT_CSS = """body{font-family:Calibri,Arial,sans-serif;color:#333;margin:30px}
h1{color:#1F4E79}h2{color:#2E75B6}
table{border-collapse:collapse;width:100%;margin:10px 0}
th{background:#1F4E79;color:#fff;padding:8px 12px;text-align:left}
td{padding:6px 12px;border:1px solid #ddd}
tr:nth-child(even){background:#f5f5f5}
.CRITICAL,.EXPIRED{color:#9C0006;background:#FFC7CE;font-weight:bold}
.HIGH{color:#9C6500;background:#FFEB9C;font-weight:bold}
.MEDIUM{color:#7D6608;background:#FFFACD}
.LOW,.OK{color:#276221;background:#C6EFCE}
.badge{display:inline-block;padding:2px 8px;border-radius:3px;font-size:11px}"""


class ReportGenerator:

    def __init__(self, logger=None):
        self.log = logger or get_logger()

    def generate_all(self, records: list, analysis: dict = None, output_dir: str = "reports"):
        """Generate all report formats."""
        os.makedirs(output_dir, exist_ok=True)
        run_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        paths = {}

        paths["markdown"] = self._write_markdown(records, analysis, output_dir, run_date)
        paths["html"] = self._write_html(records, analysis, output_dir, run_date)
        paths["csv"] = self._write_csv(records, output_dir)
        paths["json"] = self._write_json(records, analysis, output_dir, run_date)

        self.log.info("Reports generated:")
        for fmt, path in paths.items():
            self.log.info("  %-8s: %s", fmt.upper(), path)
        return paths

    def _write_markdown(self, records, analysis, output_dir, run_date):
        path = os.path.join(output_dir, "OperationsReport.md")
        risk_icons = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢", "OK": "✅", "EXPIRED": "💀"}
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"# SSL Certificate Operations Report\n\n")
            f.write(f"**Generated:** {run_date} | **Total:** {len(records)}\n\n")
            if analysis:
                f.write(f"**Overall Risk:** {analysis.get('overall_risk', 'UNKNOWN')}\n\n")
            f.write("| Domain | Certificate | Key Vault | App Service | Expires | Days | Risk |\n")
            f.write("|---|---|---|---|---|---|---|\n")
            for r in sorted(records, key=lambda x: x.days_until_expiry or 9999):
                d = r.to_dict()
                icon = risk_icons.get(d["risk_level"], "⚪")
                f.write(f"| {d['domain']} | {d['cert_name']} | {d['key_vault']} | {d['app_service']} | {d['expiration']} | {d['days_until_expiry']} | {icon} {d['risk_level']} |\n")
        return path

    def _write_html(self, records, analysis, output_dir, run_date):
        path = os.path.join(output_dir, "OperationsReport.html")
        rows = ""
        for r in sorted(records, key=lambda x: x.days_until_expiry or 9999):
            d = r.to_dict()
            risk = d["risk_level"]
            rows += f"""<tr>
<td>{d['domain']}</td><td>{d['cert_name']}</td><td>{d['key_vault']}</td>
<td>{d['app_service']}</td><td>{d['expiration']}</td><td>{d['days_until_expiry']}</td>
<td><span class="badge {risk}">{risk}</span></td>
</tr>"""
        overall = analysis.get("overall_risk", "UNKNOWN") if analysis else "UNKNOWN"
        html = f"""<!DOCTYPE html><html><head>
<meta charset="utf-8"><title>SSL Certificate Report</title>
<style>{REPORT_CSS}</style></head><body>
<h1>SSL Certificate Lifecycle Report</h1>
<p><strong>Generated:</strong> {run_date} | <strong>Total Certificates:</strong> {len(records)} | <strong>Overall Risk:</strong> <span class="{overall}">{overall}</span></p>
<h2>Certificate Inventory</h2>
<table><thead><tr>
<th>Domain</th><th>Certificate</th><th>Key Vault</th>
<th>App Service</th><th>Expires</th><th>Days Left</th><th>Risk</th>
</tr></thead><tbody>{rows}</tbody></table>
<hr><p><em>Generated by SSL Certificate Lifecycle Platform v1.0.0</em></p>
</body></html>"""
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        return path

    def _write_csv(self, records, output_dir):
        path = os.path.join(output_dir, "OperationsReport.csv")
        headers = ["Domain", "Certificate", "Key Vault", "App Service", "Expiration",
                   "Days Until Expiry", "Risk Level", "Thumbprint", "Issuer", "Version",
                   "Enabled", "Binding Status", "Last Checked"]
        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=headers)
            w.writeheader()
            for r in records:
                d = r.to_dict()
                w.writerow({
                    "Domain": d["domain"], "Certificate": d["cert_name"],
                    "Key Vault": d["key_vault"], "App Service": d["app_service"],
                    "Expiration": d["expiration"], "Days Until Expiry": d["days_until_expiry"],
                    "Risk Level": d["risk_level"], "Thumbprint": d["thumbprint"],
                    "Issuer": d["issuer"], "Version": d["version"],
                    "Enabled": d["enabled"], "Binding Status": d["binding_status"],
                    "Last Checked": d["last_checked"],
                })
        return path

    def _write_json(self, records, analysis, output_dir, run_date):
        path = os.path.join(output_dir, "OperationsReport.json")
        payload = {
            "generated": run_date,
            "total": len(records),
            "risk_analysis": analysis or {},
            "certificates": [r.to_dict() for r in records],
        }
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, default=str)
        return path

